#!/bin/sh
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit 1
exec deno run --config "$script_dir/deno.jsonc" \
  --allow-read --allow-write --allow-env --allow-net "$script_dir/cslw.ts" "$@"
