name: Checks

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Specs audit
        uses: justinmchase/specs@v1
